# Generated by Django 4.2.3 on 2023-07-25 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=100, unique=True)),
                ('modal', models.CharField(max_length=100)),
                ('rate', models.CharField(default='1', max_length=10)),
                ('cpu', models.CharField(default='Corei7-12th', max_length=100)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeBreaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRamHard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StorgeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.typeramhard')),
            ],
        ),
        migrations.CreateModel(
            name='RamDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.typeramhard')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stpes', models.CharField(max_length=300)),
                ('cost', models.CharField(max_length=20)),
                ('datein', models.DateField(null=True)),
                ('dateout', models.DateField(null=True)),
                ('TypeBreak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.typebreaks')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.device')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default='المشتل', max_length=200)),
                ('phone', models.IntegerField()),
                ('empnumber', models.IntegerField(unique=True)),
                ('PublicAd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.publicad')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='Employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.employe'),
        ),
        migrations.AddField(
            model_name='device',
            name='RamDevice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.ramdevice'),
        ),
        migrations.AddField(
            model_name='device',
            name='StorgeDevice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.storgedevice'),
        ),
        migrations.AddField(
            model_name='device',
            name='TypeDevice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EMPDEV.typedevice'),
        ),
    ]
