# Generated by Django 4.2.3 on 2023-07-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMPDEV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintainaces',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
